---
- hosts: localhost
  tasks:
  - name: create a directory
    file:
      path: "../results/"
      state: directory

  - name: populate directory    
    file:
      path: "../results/{{item}}"
      state: touch

    with_items:
      - test_01.txt
      - test_02.txt
      - test_03.txt

